install.packages("BiocManager")
BiocManager::install("biocLite")
BiocManager::install("limma")
BiocManager::install("affy")
BiocManager::install("xtable")
library(limma)
library(affy)
library(xtable)
setwd("~/dataset/folder")  
targets <-readTargets("class.txt", sep="")
abatch <- ReadAffy(filenames=targets$filename)
eset <- rma(abatch) 
f <- paste(targets$specimen,sep="")
f <- factor(f)
design <- model.matrix(~0+f)
colnames(design) <- levels(f)
fit <- lmFit(eset, design)
contrast.matrix <- makeContrasts(diseasevscontrol=T-N, levels=design) 
contrast.matrix
fit2  <- contrasts.fit(fit, contrast.matrix)
fit2  <- eBayes(fit2)
colnames(fit2)
write.table(topTable(fit2, coef= "diseasevscontrol", adjust="fdr", number=54675), file="result.xls", row.names=T, sep="\t")
